### ISSUE TITLE
SyntaxError: BeautifulSoup 4.3.2

### ISSUE THREAD

**Issue by 7stud** [bdoms/beautifulsoup#1]
Running a program with python3.4 that imports bs4 (version 4.3.2) produces this error:

<pre>
Traceback (most recent call last):
  File "1.py", line 1, in <module>
    from bs4 import BeautifulSoup
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/bs4/__init__.py", line 175
    except Exception, e:
                    ^
SyntaxError: invalid syntax
</pre>

The file mentioned in the error message has this as the top:
<pre>
"""Beautiful Soup
Elixir and Tonic
"The Screen-Scraper's Friend"
http://www.crummy.com/software/BeautifulSoup/

Beautiful Soup uses a pluggable XML or HTML parser to parse a
(possibly invalid) document into a tree representation. Beautiful Soup
provides provides methods and Pythonic idioms that make it easy to
navigate, search, and modify the parse tree.

Beautiful Soup works with Python 2.6 and up. It works better if lxml
and/or html5lib is installed.

For more than you ever wanted to know about Beautiful Soup, see the
documentation:
http://www.crummy.com/software/BeautifulSoup/bs4/doc/
"""

__author__ = "Leonard Richardson (leonardr@segfault.org)"
__version__ = "4.3.2"
</pre>
Note the version number on the last line.  And line 175 is as mention in the error message:
<pre>
            try:
                is_file = os.path.exists(possible_filename)
175 --->    except Exception, e:
                # This is almost certainly a problem involving
                # characters not valid in filenames on this
                # system. Just let it go.
                pass

</pre>

As per PEP 3110, that except statement syntax is illegal in python3.  It should be:

<pre>
 except Exception as e:
</pre>

Hmm...if I change that to the correct syntax, then the next error is:

<pre>
Traceback (most recent call last):
  File "1.py", line 1, in <module>
    from bs4 import BeautifulSoup
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/bs4/__init__.py", line 406
    print soup.prettify()
             ^
SyntaxError: invalid syntax
</pre>

The print statement is not python3 syntax.  And if I change that print statement to use parenthesis, then I get the error:

<pre>
Traceback (most recent call last):
  File "1.py", line 1, in <module>
    from bs4 import BeautifulSoup
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/bs4/builder/__init__.py", line 4, in <module>
    from bs4.element import (
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/bs4/element.py", line 1213
    print 'Running CSS selector "%s"' % selector
                                    ^
SyntaxError: Missing parentheses in call to 'print'
</pre>

It seems to me that something is seriously wrong here.  Time to try re-installing.  

I renamed the two bs4 files in the site-packages directory:
<pre>
beautifulsoup4-4.3.2-py3.4.egg-info
bs4 (a directory)
</pre>

Then I used pip to install bs4:

<pre>
$ pip3.4 install beautifulsoup4
</pre>

...and now everything is working. :)

Previously, I believe I downloaded the tar.gz file and installed with:

<pre>
 python3.4 setup.py install
</pre>

Obviously, something went wrong somewhere.

**Comment by bdoms** [comment]
This project is just a mirror of BeautifulSoup, and right now it's locked at version 3.2.0. The place to file bugs is where the project actually lives on launchpad: https://bugs.launchpad.net/beautifulsoup/
